
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.imgcodecs.Imgcodecs;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rodolffo
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        BotaoConversaoRGBYIQ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotaoBandasIndividuais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotaoNegativo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BotaoBrilhoAditivo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BotaoBrilhoMultiplicativo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BotaoLimiarizacao = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BotaoMedia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BotaoBordasSobel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BotaoMediana = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BotaoBordasLaplace = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        BotaoFiltros = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        BotaoCarregarImagem = new javax.swing.JPanel();
        LabelCarregarImagem = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setVisible(false);
        BotaoAplicar = new javax.swing.JPanel();
        BotaoAplicar.setVisible(false);
        jLabel11 = new javax.swing.JLabel();
        LabelImagemOriginal = new javax.swing.JLabel();
        LabelImagemOriginal.setVisible(false);
        LabelImagemAlterada = new javax.swing.JLabel();
        LabelImagemAlterada.setVisible(false);
        LabelImagemAlterada.setVerticalTextPosition(JLabel.BOTTOM);
        LabelImagemAlterada2 = new javax.swing.JLabel();
        LabelImagemAlterada2.setVisible(false);
        LabelImagemAlterada2.setVerticalTextPosition(JLabel.BOTTOM);
        LabelImagemAlterada3 = new javax.swing.JLabel();
        LabelImagemAlterada3.setVisible(false);
        LabelImagemAlterada3.setVerticalTextPosition(JLabel.BOTTOM);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho PDI");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 327067));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1084, 742));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(6, 60, 83));

        BotaoConversaoRGBYIQ.setBackground(new java.awt.Color(6, 60, 83));
        BotaoConversaoRGBYIQ.setPreferredSize(new java.awt.Dimension(359, 49));
        BotaoConversaoRGBYIQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoConversaoRGBYIQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoConversaoRGBYIQMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoConversaoRGBYIQMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoConversaoRGBYIQMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Conversão RGB-YIQ-RGB");

        javax.swing.GroupLayout BotaoConversaoRGBYIQLayout = new javax.swing.GroupLayout(BotaoConversaoRGBYIQ);
        BotaoConversaoRGBYIQ.setLayout(BotaoConversaoRGBYIQLayout);
        BotaoConversaoRGBYIQLayout.setHorizontalGroup(
            BotaoConversaoRGBYIQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoConversaoRGBYIQLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BotaoConversaoRGBYIQLayout.setVerticalGroup(
            BotaoConversaoRGBYIQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoConversaoRGBYIQLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoBandasIndividuais.setBackground(new java.awt.Color(6, 60, 83));
        BotaoBandasIndividuais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBandasIndividuaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoBandasIndividuaisMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoBandasIndividuaisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoBandasIndividuaisMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bandas individuais");

        javax.swing.GroupLayout BotaoBandasIndividuaisLayout = new javax.swing.GroupLayout(BotaoBandasIndividuais);
        BotaoBandasIndividuais.setLayout(BotaoBandasIndividuaisLayout);
        BotaoBandasIndividuaisLayout.setHorizontalGroup(
            BotaoBandasIndividuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBandasIndividuaisLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        BotaoBandasIndividuaisLayout.setVerticalGroup(
            BotaoBandasIndividuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        BotaoNegativo.setBackground(new java.awt.Color(6, 60, 83));
        BotaoNegativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoNegativoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoNegativoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoNegativoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoNegativoMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Negativo");

        javax.swing.GroupLayout BotaoNegativoLayout = new javax.swing.GroupLayout(BotaoNegativo);
        BotaoNegativo.setLayout(BotaoNegativoLayout);
        BotaoNegativoLayout.setHorizontalGroup(
            BotaoNegativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoNegativoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(827, Short.MAX_VALUE))
        );
        BotaoNegativoLayout.setVerticalGroup(
            BotaoNegativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoNegativoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoBrilhoAditivo.setBackground(new java.awt.Color(6, 60, 83));
        BotaoBrilhoAditivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBrilhoAditivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoBrilhoAditivoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoBrilhoAditivoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoBrilhoAditivoMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Brilho aditivo");

        javax.swing.GroupLayout BotaoBrilhoAditivoLayout = new javax.swing.GroupLayout(BotaoBrilhoAditivo);
        BotaoBrilhoAditivo.setLayout(BotaoBrilhoAditivoLayout);
        BotaoBrilhoAditivoLayout.setHorizontalGroup(
            BotaoBrilhoAditivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBrilhoAditivoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoBrilhoAditivoLayout.setVerticalGroup(
            BotaoBrilhoAditivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBrilhoAditivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoBrilhoMultiplicativo.setBackground(new java.awt.Color(6, 60, 83));
        BotaoBrilhoMultiplicativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBrilhoMultiplicativoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoBrilhoMultiplicativoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoBrilhoMultiplicativoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoBrilhoMultiplicativoMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Brilho multiplicativo");

        javax.swing.GroupLayout BotaoBrilhoMultiplicativoLayout = new javax.swing.GroupLayout(BotaoBrilhoMultiplicativo);
        BotaoBrilhoMultiplicativo.setLayout(BotaoBrilhoMultiplicativoLayout);
        BotaoBrilhoMultiplicativoLayout.setHorizontalGroup(
            BotaoBrilhoMultiplicativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBrilhoMultiplicativoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoBrilhoMultiplicativoLayout.setVerticalGroup(
            BotaoBrilhoMultiplicativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBrilhoMultiplicativoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoLimiarizacao.setBackground(new java.awt.Color(6, 60, 83));
        BotaoLimiarizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoLimiarizacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoLimiarizacaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoLimiarizacaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoLimiarizacaoMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Limiarização");

        javax.swing.GroupLayout BotaoLimiarizacaoLayout = new javax.swing.GroupLayout(BotaoLimiarizacao);
        BotaoLimiarizacao.setLayout(BotaoLimiarizacaoLayout);
        BotaoLimiarizacaoLayout.setHorizontalGroup(
            BotaoLimiarizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoLimiarizacaoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoLimiarizacaoLayout.setVerticalGroup(
            BotaoLimiarizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoLimiarizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoMedia.setBackground(new java.awt.Color(6, 60, 83));
        BotaoMedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoMediaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoMediaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoMediaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoMediaMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Filtro de média");

        javax.swing.GroupLayout BotaoMediaLayout = new javax.swing.GroupLayout(BotaoMedia);
        BotaoMedia.setLayout(BotaoMediaLayout);
        BotaoMediaLayout.setHorizontalGroup(
            BotaoMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoMediaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoMediaLayout.setVerticalGroup(
            BotaoMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoMediaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoBordasSobel.setBackground(new java.awt.Color(6, 60, 83));
        BotaoBordasSobel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBordasSobelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoBordasSobelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoBordasSobelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoBordasSobelMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Detecção de bordas Sobel");

        javax.swing.GroupLayout BotaoBordasSobelLayout = new javax.swing.GroupLayout(BotaoBordasSobel);
        BotaoBordasSobel.setLayout(BotaoBordasSobelLayout);
        BotaoBordasSobelLayout.setHorizontalGroup(
            BotaoBordasSobelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBordasSobelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoBordasSobelLayout.setVerticalGroup(
            BotaoBordasSobelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBordasSobelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoMediana.setBackground(new java.awt.Color(6, 60, 83));
        BotaoMediana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoMedianaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoMedianaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoMedianaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoMedianaMouseReleased(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(6, 60, 83));
        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Filtro de mediana");

        javax.swing.GroupLayout BotaoMedianaLayout = new javax.swing.GroupLayout(BotaoMediana);
        BotaoMediana.setLayout(BotaoMedianaLayout);
        BotaoMedianaLayout.setHorizontalGroup(
            BotaoMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoMedianaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoMedianaLayout.setVerticalGroup(
            BotaoMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoMedianaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoBordasLaplace.setBackground(new java.awt.Color(6, 60, 83));
        BotaoBordasLaplace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoBordasLaplaceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoBordasLaplaceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoBordasLaplaceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoBordasLaplaceMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Detecção de bordas Laplace");

        javax.swing.GroupLayout BotaoBordasLaplaceLayout = new javax.swing.GroupLayout(BotaoBordasLaplace);
        BotaoBordasLaplace.setLayout(BotaoBordasLaplaceLayout);
        BotaoBordasLaplaceLayout.setHorizontalGroup(
            BotaoBordasLaplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBordasLaplaceLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoBordasLaplaceLayout.setVerticalGroup(
            BotaoBordasLaplaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoBordasLaplaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotaoFiltros.setBackground(new java.awt.Color(6, 60, 83));
        BotaoFiltros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoFiltrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoFiltrosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoFiltrosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoFiltrosMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Filtros ");

        javax.swing.GroupLayout BotaoFiltrosLayout = new javax.swing.GroupLayout(BotaoFiltros);
        BotaoFiltros.setLayout(BotaoFiltrosLayout);
        BotaoFiltrosLayout.setHorizontalGroup(
            BotaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoFiltrosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        BotaoFiltrosLayout.setVerticalGroup(
            BotaoFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotaoConversaoRGBYIQ, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoBandasIndividuais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoNegativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBrilhoAditivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBrilhoMultiplicativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLimiarizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBordasSobel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBordasLaplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(BotaoConversaoRGBYIQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBandasIndividuais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoNegativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBrilhoAditivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBrilhoMultiplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoLimiarizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBordasSobel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBordasLaplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        BotaoCarregarImagem.setBackground(new java.awt.Color(255, 255, 255));
        BotaoCarregarImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoCarregarImagemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoCarregarImagemMouseReleased(evt);
            }
        });

        LabelCarregarImagem.setBackground(new java.awt.Color(255, 255, 255));
        LabelCarregarImagem.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        LabelCarregarImagem.setForeground(new java.awt.Color(6, 60, 83));
        LabelCarregarImagem.setText("Carregar Imagem");

        javax.swing.GroupLayout BotaoCarregarImagemLayout = new javax.swing.GroupLayout(BotaoCarregarImagem);
        BotaoCarregarImagem.setLayout(BotaoCarregarImagemLayout);
        BotaoCarregarImagemLayout.setHorizontalGroup(
            BotaoCarregarImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoCarregarImagemLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(LabelCarregarImagem)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        BotaoCarregarImagemLayout.setVerticalGroup(
            BotaoCarregarImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoCarregarImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCarregarImagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField1.setText("Digite o valor do brilho");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });

        BotaoAplicar.setBackground(new java.awt.Color(6, 60, 83));
        BotaoAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotaoAplicarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotaoAplicarMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Aplicar");

        javax.swing.GroupLayout BotaoAplicarLayout = new javax.swing.GroupLayout(BotaoAplicar);
        BotaoAplicar.setLayout(BotaoAplicarLayout);
        BotaoAplicarLayout.setHorizontalGroup(
            BotaoAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoAplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotaoAplicarLayout.setVerticalGroup(
            BotaoAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        LabelImagemOriginal.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        LabelImagemOriginal.setText("1");
        LabelImagemOriginal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LabelImagemOriginal.setFocusable(false);
        LabelImagemOriginal.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        LabelImagemAlterada.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        LabelImagemAlterada.setText("2");
        LabelImagemAlterada.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabelImagemAlterada.setFocusable(false);
        LabelImagemAlterada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LabelImagemAlterada2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        LabelImagemAlterada2.setText("3");
        LabelImagemAlterada2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabelImagemAlterada2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LabelImagemAlterada3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        LabelImagemAlterada3.setText("4");
        LabelImagemAlterada3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabelImagemAlterada3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setText("IMAGEM ORIGINAL:");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("IMAGEM ALTERADA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelImagemOriginal)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LabelImagemAlterada)
                                        .addGap(34, 34, 34)
                                        .addComponent(LabelImagemAlterada2)
                                        .addGap(34, 34, 34)
                                        .addComponent(LabelImagemAlterada3))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(448, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(BotaoCarregarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 209, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelImagemOriginal)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelImagemAlterada)
                    .addComponent(LabelImagemAlterada2)
                    .addComponent(LabelImagemAlterada3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(BotaoCarregarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCarregarImagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCarregarImagemMouseReleased
        BotaoCarregarImagem.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_BotaoCarregarImagemMouseReleased

    private void BotaoCarregarImagemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCarregarImagemMousePressed
        BotaoCarregarImagem.setBackground(Color.decode("#bcbcbc"));

        String endereco = "src\\Imagens\\";
        JFileChooser jfc = new JFileChooser(endereco);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG images", "jpg");
        jfc.setFileFilter(filter);
        
        
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            endereco += jfc.getName(jfc.getSelectedFile());
            
            this.imagemOriginal = Imgcodecs.imread(endereco);

            jTextField1.setVisible(false);
            BotaoAplicar.setVisible(false);
            LabelImagemOriginal.setVisible(true);
            LabelImagemOriginal.setText("");
            LabelImagemAlterada.setVisible(false);
            LabelImagemAlterada2.setVisible(false);
            LabelImagemAlterada3.setVisible(false);
            
            
            
            iconOriginal = new ImageIcon(Metodos.toBufferedImage(imagemOriginal));
            
            //LabelImagemOriginal.setIcon(iconOriginal);
            
            image = iconOriginal.getImage();  
            newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
            LabelImagemOriginal.setIcon(new ImageIcon(newimg));
            
            
        }else{
            imagemCarregada = "";
            CaminhoImagemCarregada = "";
            imagemOriginal = null;
        
        }
    }//GEN-LAST:event_BotaoCarregarImagemMousePressed

    //BOTÃO CONVERSOR RGB-YIQ
    private void BotaoConversaoRGBYIQMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoConversaoRGBYIQMouseReleased
        BotaoConversaoRGBYIQ.setBackground(released);
    }//GEN-LAST:event_BotaoConversaoRGBYIQMouseReleased

    private void BotaoConversaoRGBYIQMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoConversaoRGBYIQMousePressed
        BotaoConversaoRGBYIQ.setBackground(pressed);

        jTextField1.setVisible(false);
        BotaoAplicar.setVisible(false);
        LabelImagemAlterada.setVisible(true);
        LabelImagemAlterada.setText("");
        LabelImagemAlterada2.setVisible(false);
        LabelImagemAlterada2.setText("");
        LabelImagemAlterada3.setVisible(false);

        imagemAlterada = Metodos.converterRGBYIQ(imagemOriginal);  
        imagemAlterada = Metodos.converterYIQRGB(imagemAlterada);
        iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
        //LabelImagemAlterada.setIcon(iconAlterado);
        
        image = iconAlterado.getImage();  
        newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
        LabelImagemAlterada.setIcon(new ImageIcon(newimg));
    }//GEN-LAST:event_BotaoConversaoRGBYIQMousePressed

    private void BotaoConversaoRGBYIQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoConversaoRGBYIQMouseExited
        BotaoConversaoRGBYIQ.setBackground(released);
    }//GEN-LAST:event_BotaoConversaoRGBYIQMouseExited

    private void BotaoConversaoRGBYIQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoConversaoRGBYIQMouseEntered
        BotaoConversaoRGBYIQ.setBackground(entered);
    }//GEN-LAST:event_BotaoConversaoRGBYIQMouseEntered

    //BOTÃO BANDAS INDIVIDUAIS
    private void BotaoBandasIndividuaisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBandasIndividuaisMouseReleased
        BotaoBandasIndividuais.setBackground(released);
    }//GEN-LAST:event_BotaoBandasIndividuaisMouseReleased

    private void BotaoBandasIndividuaisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBandasIndividuaisMousePressed
        BotaoBandasIndividuais.setBackground(pressed);

        jTextField1.setVisible(false);
        BotaoAplicar.setVisible(false);
        LabelImagemAlterada.setVisible(true);
        LabelImagemAlterada.setText("Red");
        LabelImagemAlterada2.setVisible(true);
        LabelImagemAlterada2.setText("Green");
        LabelImagemAlterada3.setVisible(true);
        LabelImagemAlterada3.setText("Blue");

        imagemAlterada = Metodos.bandaR(imagemOriginal);
        iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
        LabelImagemAlterada.setIcon(iconAlterado);
        
//        image = iconAlterado.getImage();  
//        newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
//        LabelImagemAlterada.setIcon(new ImageIcon(newimg));

        imagemAlterada = Metodos.bandaG(imagemOriginal);
        iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
        LabelImagemAlterada2.setIcon(iconAlterado);
        
//        image = iconAlterado.getImage();  
//        newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
//        LabelImagemAlterada2.setIcon(new ImageIcon(newimg));

        imagemAlterada = Metodos.bandaG(imagemOriginal);
        iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
        LabelImagemAlterada3.setIcon(iconAlterado);
        
//        image = iconAlterado.getImage();  
//        newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
//        LabelImagemAlterada3.setIcon(new ImageIcon(newimg));

    }//GEN-LAST:event_BotaoBandasIndividuaisMousePressed

    private void BotaoBandasIndividuaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBandasIndividuaisMouseExited
        BotaoBandasIndividuais.setBackground(released);
    }//GEN-LAST:event_BotaoBandasIndividuaisMouseExited

    private void BotaoBandasIndividuaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBandasIndividuaisMouseEntered
        BotaoBandasIndividuais.setBackground(entered);
    }//GEN-LAST:event_BotaoBandasIndividuaisMouseEntered

    // BOTAO NEGATIVO
    private void BotaoNegativoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoNegativoMouseEntered
        BotaoNegativo.setBackground(entered);
    }//GEN-LAST:event_BotaoNegativoMouseEntered

    private void BotaoNegativoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoNegativoMouseExited
        BotaoNegativo.setBackground(released);
    }//GEN-LAST:event_BotaoNegativoMouseExited

    private void BotaoNegativoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoNegativoMousePressed
        BotaoNegativo.setBackground(pressed);
        
        jTextField1.setVisible(false);
        BotaoAplicar.setVisible(false);
        LabelImagemAlterada.setVisible(true);
        LabelImagemAlterada.setText("Negativo em RGB:");
        LabelImagemAlterada2.setVisible(true);
        LabelImagemAlterada2.setText("Negativo em YIQ com retorno para RGB:");
        LabelImagemAlterada3.setVisible(false);
        LabelImagemAlterada3.setText("");

        //negativo da imagem rgb
        imagemAlterada = Metodos.negativoRGB(imagemOriginal);
        iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
        //LabelImagemAlterada.setIcon(iconAlterado);
        
        image = iconAlterado.getImage();  
        newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
        LabelImagemAlterada.setIcon(new ImageIcon(newimg));
  
        //negativo aplicado a imagem yiq e depois tranformada para rgb
        imagemAlterada = Metodos.converterRGBYIQ(imagemOriginal);                               
        imagemAlterada = Metodos.negativoYIQ(imagemAlterada);
        imagemAlterada = Metodos.converterYIQRGB(imagemAlterada);
        iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
        //LabelImagemAlterada2.setIcon(iconAlterado);
        
        image = iconAlterado.getImage();  
        newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
        LabelImagemAlterada2.setIcon(new ImageIcon(newimg));
    }//GEN-LAST:event_BotaoNegativoMousePressed

    private void BotaoNegativoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoNegativoMouseReleased
        BotaoNegativo.setBackground(released);
    }//GEN-LAST:event_BotaoNegativoMouseReleased

    private void BotaoBrilhoAditivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoAditivoMouseEntered
         BotaoBrilhoAditivo.setBackground(entered);
    }//GEN-LAST:event_BotaoBrilhoAditivoMouseEntered

    private void BotaoBrilhoAditivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoAditivoMouseExited
        BotaoBrilhoAditivo.setBackground(released);
    }//GEN-LAST:event_BotaoBrilhoAditivoMouseExited

    private void BotaoBrilhoAditivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoAditivoMousePressed
        BotaoBrilhoAditivo.setBackground(pressed);
        jTextField1.setVisible(true);
        jTextField1.setText("Digite o valor do brilho aditivo");
        BotaoAplicar.setVisible(true);
        LabelImagemAlterada.setVisible(false);
        LabelImagemAlterada.setText("");
        LabelImagemAlterada2.setVisible(false);
        LabelImagemAlterada2.setText("");
        LabelImagemAlterada3.setVisible(false);
        LabelImagemAlterada3.setText("");
        opcao = 4;
    }//GEN-LAST:event_BotaoBrilhoAditivoMousePressed

    private void BotaoBrilhoAditivoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoAditivoMouseReleased
        BotaoBrilhoAditivo.setBackground(released);
    }//GEN-LAST:event_BotaoBrilhoAditivoMouseReleased

    // BOTAO BRILHO MULTIPLICATIVO
    private void BotaoBrilhoMultiplicativoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoMultiplicativoMouseEntered
        BotaoBrilhoMultiplicativo.setBackground(entered);
    }//GEN-LAST:event_BotaoBrilhoMultiplicativoMouseEntered

    private void BotaoBrilhoMultiplicativoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoMultiplicativoMouseExited
        BotaoBrilhoMultiplicativo.setBackground(released);
    }//GEN-LAST:event_BotaoBrilhoMultiplicativoMouseExited

    private void BotaoBrilhoMultiplicativoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoMultiplicativoMousePressed
        BotaoBrilhoMultiplicativo.setBackground(pressed);
        jTextField1.setVisible(true);
        jTextField1.setText("Digite o valor do brilho multiplicativo");
        BotaoAplicar.setVisible(true);
        LabelImagemAlterada.setVisible(false);
        LabelImagemAlterada.setText("");
        LabelImagemAlterada2.setVisible(false);
        LabelImagemAlterada2.setText("");
        LabelImagemAlterada3.setVisible(false);
        LabelImagemAlterada3.setText("");
        opcao = 5;
        
    }//GEN-LAST:event_BotaoBrilhoMultiplicativoMousePressed

    private void BotaoBrilhoMultiplicativoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBrilhoMultiplicativoMouseReleased
        BotaoBrilhoMultiplicativo.setBackground(released);
    }//GEN-LAST:event_BotaoBrilhoMultiplicativoMouseReleased

    // BOTÃO LIMIARIZAÇÃO
    private void BotaoLimiarizacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimiarizacaoMouseEntered
        BotaoLimiarizacao.setBackground(entered);
    }//GEN-LAST:event_BotaoLimiarizacaoMouseEntered

    private void BotaoLimiarizacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimiarizacaoMouseExited
        BotaoLimiarizacao.setBackground(released);
    }//GEN-LAST:event_BotaoLimiarizacaoMouseExited

    private void BotaoLimiarizacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimiarizacaoMousePressed
        BotaoLimiarizacao.setBackground(pressed);
        jTextField1.setVisible(true);
        jTextField1.setText("Digite o valor do limiar");
        BotaoAplicar.setVisible(true);
        LabelImagemAlterada.setVisible(false);
        LabelImagemAlterada.setText("");
        LabelImagemAlterada2.setVisible(false);
        LabelImagemAlterada2.setText("");
        LabelImagemAlterada3.setVisible(false);
        LabelImagemAlterada3.setText("");
        opcao = 6;
        
    }//GEN-LAST:event_BotaoLimiarizacaoMousePressed

    private void BotaoLimiarizacaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimiarizacaoMouseReleased
        BotaoLimiarizacao.setBackground(released);
    }//GEN-LAST:event_BotaoLimiarizacaoMouseReleased

    // BOTÃO MEDIA
    private void BotaoMediaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMediaMouseEntered
        BotaoMedia.setBackground(entered);
    }//GEN-LAST:event_BotaoMediaMouseEntered

    private void BotaoMediaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMediaMouseExited
       BotaoMedia.setBackground(released);
    }//GEN-LAST:event_BotaoMediaMouseExited

    private void BotaoMediaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMediaMousePressed
        BotaoMedia.setBackground(pressed);
        
        jTextField1.setVisible(true);
        jTextField1.setText("Digite o valor do kernel");
        BotaoAplicar.setVisible(true);
        LabelImagemAlterada.setVisible(false);
        LabelImagemAlterada.setText("");
        LabelImagemAlterada2.setVisible(false);
        LabelImagemAlterada2.setText("");
        LabelImagemAlterada3.setVisible(false);
        LabelImagemAlterada3.setText("");
        opcao = 7;
        
    }//GEN-LAST:event_BotaoMediaMousePressed

    private void BotaoMediaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMediaMouseReleased
        BotaoMedia.setBackground(released);
    }//GEN-LAST:event_BotaoMediaMouseReleased

    // BOTÃO DETECÇÃO DE BORDAS
    private void BotaoBordasSobelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasSobelMouseEntered
        BotaoBordasSobel.setBackground(entered);
    }//GEN-LAST:event_BotaoBordasSobelMouseEntered

    private void BotaoBordasSobelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasSobelMouseExited
        BotaoBordasSobel.setBackground(released);
    }//GEN-LAST:event_BotaoBordasSobelMouseExited

    private void BotaoBordasSobelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasSobelMousePressed
       BotaoBordasSobel.setBackground(pressed);
       
       jTextField1.setVisible(false);
       BotaoAplicar.setVisible(false);
       LabelImagemAlterada.setVisible(true);
       LabelImagemAlterada.setText("");
       LabelImagemAlterada2.setVisible(false);
       LabelImagemAlterada2.setText("");
       LabelImagemAlterada3.setVisible(false);
       LabelImagemAlterada3.setText("");
       
       imagemAlterada = Metodos.bordasSobel(imagemOriginal);
       iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
       LabelImagemAlterada.setIcon(iconAlterado);

       
    }//GEN-LAST:event_BotaoBordasSobelMousePressed

    private void BotaoBordasSobelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasSobelMouseReleased
       BotaoBordasSobel.setBackground(released);
    }//GEN-LAST:event_BotaoBordasSobelMouseReleased

    private void BotaoAplicarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAplicarMousePressed
        BotaoAplicar.setBackground(pressed);
        Double valor;
        int tam;
           
        switch(opcao){
            case 4:
                LabelImagemAlterada.setVisible(true);
                LabelImagemAlterada.setText("Brilho aplicado nas bandas RGB:");
                LabelImagemAlterada2.setVisible(true);
                LabelImagemAlterada2.setText("Brilho aplicado na banda Y:");
        
                valor = Double.parseDouble(jTextField1.getText());
                jTextField1.setText("Digite o valor do brilho aditivo");
                
                //Brilho Soma RGB
                imagemAlterada = Metodos.brilhoSomaRGB(imagemOriginal, valor);
                iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
                LabelImagemAlterada.setIcon(iconAlterado);
                
                image = iconAlterado.getImage();  
                newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
                LabelImagemAlterada.setIcon(new ImageIcon(newimg));
                
                //#################################################################################
                
                //Brilho Soma RGB-YIQ-RGB
                //Primeiro converte pra YIQ
                imagemAlterada = Metodos.converterRGBYIQ(imagemOriginal);
                //Aplica o brilho ainda em YIQ                                   
                imagemAlterada = Metodos.brilhoSomaYIQ(imagemAlterada, valor);
                //Depois de aplicar o brilho, volta para RGB
                imagemAlterada = Metodos.converterYIQRGB(imagemAlterada);
                
                iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
                LabelImagemAlterada2.setIcon(iconAlterado);
                
                image = iconAlterado.getImage();  
                newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
                LabelImagemAlterada2.setIcon(new ImageIcon(newimg));
                
                
                break;
                
            case 5:
                LabelImagemAlterada.setVisible(true);
                LabelImagemAlterada.setText("Brilho aplicado nas bandas RGB");
                LabelImagemAlterada2.setVisible(true);
                LabelImagemAlterada2.setText("Brilho aplicado na banda Y");
                
                valor = Double.parseDouble(jTextField1.getText());
                jTextField1.setText("Digite o valor do brilho multiplicativo");
                
                //Brilh multiplicação RGB
                imagemAlterada = Metodos.brilhoMultiplicacaoRGB(imagemOriginal, valor);
                iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
                //LabelImagemAlterada.setIcon(iconAlterado);
                
                image = iconAlterado.getImage();  
                newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
                LabelImagemAlterada.setIcon(new ImageIcon(newimg));
                
                //#################################################################################
                
                //Brilho multiplicação RGB-YIQ-RGB
                //Primeiro converte pra YIQ
                imagemAlterada = Metodos.converterRGBYIQ(imagemOriginal);
                //Aplica o brilho ainda em YIQ                                   
                imagemAlterada = Metodos.brilhoMultiplicacaoYIQ(imagemAlterada, valor);
                //Depois de aplicar o brilho, volta para RGB
                imagemAlterada = Metodos.converterYIQRGB(imagemAlterada);
                
                iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
                LabelImagemAlterada2.setIcon(iconAlterado);  
                
                image = iconAlterado.getImage();  
                newimg = image.getScaledInstance(300, 168, java.awt.Image.SCALE_SMOOTH);  
                LabelImagemAlterada2.setIcon(new ImageIcon(newimg));
                
                break;
                
            case 6:
                LabelImagemAlterada.setVisible(true);
                LabelImagemAlterada.setText("");
                
                try{
                    tam = Integer.parseInt(jTextField1.getText());
                }catch (NumberFormatException e){
                    tam = -1;
                }
                jTextField1.setText("Digite o valor do limiar");
                imagemAlterada = Metodos.limiarizaçãoY(imagemOriginal, tam);
                iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
                LabelImagemAlterada.setIcon(iconAlterado);               
                break;
            case 7:
                LabelImagemAlterada.setVisible(true);
                LabelImagemAlterada.setText("");
                
                tam = Integer.parseInt(jTextField1.getText());
                jTextField1.setText("Digite o valor do kernel");
                imagemAlterada = Metodos.filtroMedia(imagemOriginal, tam);
                iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
                LabelImagemAlterada.setIcon(iconAlterado);
                break;
                
            case 8:
                LabelImagemAlterada.setVisible(true);
                LabelImagemAlterada.setText("");
                
                tam = Integer.parseInt(jTextField1.getText());
                jTextField1.setText("Digite o valor do kernel");
                imagemAlterada = Metodos.filtroMediana(imagemOriginal, tam);           
                iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
                LabelImagemAlterada.setIcon(iconAlterado);
                break;
        }
    }//GEN-LAST:event_BotaoAplicarMousePressed

    private void BotaoAplicarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAplicarMouseReleased
        BotaoAplicar.setBackground(released);
    }//GEN-LAST:event_BotaoAplicarMouseReleased

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MousePressed

    // BOTÃO MEDIANA
    private void BotaoMedianaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMedianaMouseEntered
        BotaoMediana.setBackground(entered);
    }//GEN-LAST:event_BotaoMedianaMouseEntered

    private void BotaoMedianaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMedianaMouseExited
        BotaoMediana.setBackground(released);
    }//GEN-LAST:event_BotaoMedianaMouseExited

    private void BotaoMedianaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMedianaMousePressed
        BotaoMediana.setBackground(pressed);
        
        jTextField1.setVisible(true);
        jTextField1.setText("Digite o valor do kernel");
        BotaoAplicar.setVisible(true);
        LabelImagemAlterada.setVisible(false);
        LabelImagemAlterada.setText("");
        LabelImagemAlterada2.setVisible(false);
        LabelImagemAlterada2.setText("");
        LabelImagemAlterada3.setVisible(false);
        LabelImagemAlterada3.setText("");
        opcao = 8;
    }//GEN-LAST:event_BotaoMedianaMousePressed

    private void BotaoMedianaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMedianaMouseReleased
        BotaoMediana.setBackground(released);
    }//GEN-LAST:event_BotaoMedianaMouseReleased

    private void BotaoBordasLaplaceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasLaplaceMouseEntered
        BotaoBordasLaplace.setBackground(entered);
    }//GEN-LAST:event_BotaoBordasLaplaceMouseEntered

    private void BotaoBordasLaplaceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasLaplaceMouseExited
        BotaoBordasLaplace.setBackground(released);
    }//GEN-LAST:event_BotaoBordasLaplaceMouseExited

    private void BotaoBordasLaplaceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasLaplaceMousePressed
       BotaoBordasLaplace.setBackground(pressed);
        
       jTextField1.setVisible(false);
       BotaoAplicar.setVisible(false);
       LabelImagemAlterada.setVisible(true);
       LabelImagemAlterada.setText("");
       LabelImagemAlterada2.setVisible(false);
       LabelImagemAlterada2.setText("");
       LabelImagemAlterada3.setVisible(false);
       LabelImagemAlterada3.setText("");
       
       imagemAlterada = Metodos.bordasLaplace(imagemOriginal);
       iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
       LabelImagemAlterada.setIcon(iconAlterado);
    }//GEN-LAST:event_BotaoBordasLaplaceMousePressed

    private void BotaoBordasLaplaceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBordasLaplaceMouseReleased
        BotaoBordasLaplace.setBackground(released);
    }//GEN-LAST:event_BotaoBordasLaplaceMouseReleased

    private void BotaoFiltrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFiltrosMouseEntered
        BotaoFiltros.setBackground(entered);
    }//GEN-LAST:event_BotaoFiltrosMouseEntered

    private void BotaoFiltrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFiltrosMouseExited
        BotaoFiltros.setBackground(released);
    }//GEN-LAST:event_BotaoFiltrosMouseExited

    private void BotaoFiltrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFiltrosMousePressed
       BotaoFiltros.setBackground(pressed);
        
       jTextField1.setVisible(false);
       BotaoAplicar.setVisible(false);
       LabelImagemAlterada.setVisible(true);
       LabelImagemAlterada.setText("Filtro 1");
       LabelImagemAlterada2.setVisible(true);
       LabelImagemAlterada2.setText("Filtro 2");
       LabelImagemAlterada3.setVisible(false);
       LabelImagemAlterada3.setText("");
       
       imagemAlterada = Metodos.filtro1(imagemOriginal);
       iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
       LabelImagemAlterada.setIcon(iconAlterado);
       
       imagemAlterada = Metodos.filtro2(imagemOriginal);
       iconAlterado = new ImageIcon(Metodos.toBufferedImage(imagemAlterada));
       LabelImagemAlterada2.setIcon(iconAlterado);
       
    }//GEN-LAST:event_BotaoFiltrosMousePressed

    private void BotaoFiltrosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFiltrosMouseReleased
        BotaoFiltros.setBackground(released);
    }//GEN-LAST:event_BotaoFiltrosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    private Image image = null;
    private Image newimg = null;
    private String imagemCarregada;
    private String CaminhoImagemCarregada;
    private ImageIcon iconOriginal;
    private Mat imagemOriginal;
    private ImageIcon iconAlterado;
    private Mat imagemAlterada;
    private int opcao;
    private Color pressed = Color.decode("#136572");
    private Color released = Color.decode("#063C53");
    private Color entered = Color.decode("#095575");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotaoAplicar;
    private javax.swing.JPanel BotaoBandasIndividuais;
    private javax.swing.JPanel BotaoBordasLaplace;
    private javax.swing.JPanel BotaoBordasSobel;
    private javax.swing.JPanel BotaoBrilhoAditivo;
    private javax.swing.JPanel BotaoBrilhoMultiplicativo;
    private javax.swing.JPanel BotaoCarregarImagem;
    private javax.swing.JPanel BotaoConversaoRGBYIQ;
    private javax.swing.JPanel BotaoFiltros;
    private javax.swing.JPanel BotaoLimiarizacao;
    private javax.swing.JPanel BotaoMedia;
    private javax.swing.JPanel BotaoMediana;
    private javax.swing.JPanel BotaoNegativo;
    private javax.swing.JLabel LabelCarregarImagem;
    private javax.swing.JLabel LabelImagemAlterada;
    private javax.swing.JLabel LabelImagemAlterada2;
    private javax.swing.JLabel LabelImagemAlterada3;
    private javax.swing.JLabel LabelImagemOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
